### ISSUE TITLE
Trouble starting services on boot in RancherOS v0.2.1

### ISSUE THREAD

**Issue by imikushin** [rancherio/os#106]
`/opt/rancher/bin/start.sh` doesn't seem to make it: vagrant up just stalls and I don't know what's going on. 
`/opt/rancher/bin/start.sh`:
```bash
#!/bin/sh
nohup /opt/rancher/bin/do-start.sh >/var/log/start.log 2>&1 &
```
`/opt/rancher/bin/do-start.sh`:
```bash
#!/bin/sh
set -x -e
docker stop nginx && docker rm nginx && :
docker run -d --name=nginx -p=8080:80 nginx
```

Both `start.sh` and `do-start.sh` are executable.

OS appears to hang on after `Running [7/13] cloud-init-pre`:
![os-vagrant_rancher-01_1427374830498_34855](https://cloud.githubusercontent.com/assets/931932/6848286/26c21126-d3ee-11e4-8c73-4b962b9a29b8.png)

**Comment by ibuildthecloud** [comment]
If  /opt/rancher/bin/start.sh fails it shouldn't fail the boot, but  /opt/rancher/bin/start.sh is actually executed by the console container.  So in this situation the reason it isn't booting is not related to you script.  If cloud-init-pre is hung that means it can't talk to the cloud config data source.  In the Vagrant setup there is a file `/var/lib/rancher/conf/user_config.yml`.  If you delete that file, the boot will hang forever.  You have to also edit rancher.yml and remove the reference to it.  This is a bug and should be fixed.

**Comment by ibuildthecloud** [comment]
I created #107 to track this issue.

**Comment by imikushin** [comment]
The file is there. I didn't delete it, just added `start.sh`. To reproduce,
just add my `start.sh` and `do-start.sh`

**Comment by imikushin** [comment]
@ibuildthecloud, actually, you are right: I just tried to reproduce this anew and it worked. 
OK, this got the boot to hang (not forever, just for a **very** long time):
```bash
# rancherctl c get cloud_init.datasources
- file:/home/rancher/cloud-init.sh
```
`cloud-init.sh` being an executable script:
```bash
#!/bin/sh
set -x -e

mkdir -p /opt/rancher/bin

cat <<EOF >/opt/rancher/bin/start.sh
#!/bin/sh
nohup /opt/rancher/bin/do-start.sh >/var/log/start.log 2>&1 &
EOF

chmod +x /opt/rancher/bin/start.sh

cat <<EOF >/opt/rancher/bin/do-start.sh
#!/bin/sh
set -x -e
docker stop nginx && docker rm nginx && :
docker run -d --name=nginx -p=8080:80 nginx
EOF

chmod +x /opt/rancher/bin/do-start.sh
```

**Comment by imikushin** [comment]
Hangs exactly the same way after this: 
```bash
rancherctl c set cloud_init.datasources [file:/home/rancher/my_config.yml]
```
`my_config.yml` contains:
```yml
#cloud-config
write_files:
- path: /opt/rancher/bin/start.sh
  permissions: 0755
  owner: root
  content: |
    #!/bin/sh
    nohup /opt/rancher/bin/do-start.sh >/var/log/start.log 2>&1 &
- path: /opt/rancher/bin/do-start.sh
  permissions: 0755
  owner: root
  content: |
    #!/bin/sh
    set -x -e
    docker stop nginx && docker rm nginx && :
    docker run -d --name=nginx -p=8080:80 nginx
```
