### ISSUE TITLE
DHCP Routes/Add Static Route

### ISSUE THREAD

**Issue by kupo24z** [rancherio/os#129]
Hello, Is there currently a way to add a static route before cloud-init begins? We have our metadata server available via the DHCP server. Normally this is provided by the DHCP configuration however on docker it looks not to be the case. If we can execute arbitrary commands this will also work;

dhcpServer=$(grep dhcp-server-identifier /var/lib/dhcp/dhclient.leases | awk '{print $3}' | cut -d ';' -f1)
ip route add 169.254.169.254/32 via $dhcpServer dev eth0

In addition, it seems there is no way to specify which interface to use the default gateway for which seems to cause a race condition. In our setup we have two interfaces both with DHCP, eth1 ends up starting second and the default gateway ends up being configured there. Ubuntu/Debian solves this with "post-up route del default dev eth1". The only workaround I have seen thus far is only enabling eth0 however since it doesn't supply all the DHCP routes, it has no metadata access (see first point).

**Comment by cloudnautique** [comment]
Hello. The way it is currently configured, if you have basic network connectivity you can pull down a container and perform network configuration tasks. This really only works IF the network comes up in the first place. We are currently switching out the Udchpc dhcpclient for the more robust client dhclient (PR #122) in the next release, which hopefully will ease some of this. 

I think we ran into a similar situation recently, which resulted in us having to do this: #125. Not a great solution for everyone else... and I'm really hoping that it goes away with #122. 

What type of install did you use? As part of the cloud-init yaml file passed to the installer, you can add a `rancher:` section. From that you can customize the network config.
We do a generic install for Vagrant with the following config:
```
        cat >/opt/user_config.yml<<EOF
#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
rancher:
  network:
    interfaces:
      eth*:
        dhcp: false
      eth0:
        dhcp: true
      lo:
        address: 127.0.0.1/8
```

Which makes it so only eth0 comes up on DHCP. You could do something similar (assuming eth0 will come up)

and do something like:
```
...
rancher:
 network:
    interfaces:
       eth*:
        dhcp: false
      eth0:
        dhcp: true
      lo:
        address: 127.0.0.1/8
    post_run:
       - id: post-networking
         run: --net=host --privileged <image> <cmd>
         createonly: false
```
inside that post-networking container you can do the more custom configurations.
