### ISSUE TITLE
cloud-init would not run services on first boot

### ISSUE THREAD

**Issue by imikushin** [rancherio/os#156]
Suppose we perform a clean RancherOS install and supply the following file (`waagent-init.yml`) as cloud-config source:
```yml
#cloud-config
rancher:
  enabled_services:
  - /var/lib/rancher/conf/waagent.yml
```
What's weird is services specified in `waagent.yml` (already in place) do not get started on the first boot, even though the cloud-config gets correctly parsed and applied. Here's how `/var/lib/rancher/conf/rancher.yml` looks:
```yml
cloud_init:
  datasources:
  - file:/var/lib/rancher/conf/waagent-init.yml
enabled_services:
- /var/lib/rancher/conf/waagent.yml
```
On the following boots the services do get run though.
