### ISSUE TITLE
Baremetal install hangs with a yaml unmarshal error

### ISSUE THREAD

**Issue by bnoon** [rancherio/os#201]
When doing a bare metal install of v0.3.0-rc4, the reboot hangs when unmarshalling `cloud-config-processed.yml`

The line points to the ssh public key.  In the .yml file, the line is split with the user@host part on the next line.  This happens for all the .yml files.  Editing these files, allows the boot to continue to completion.

The output of `sudo rancherctl config export -p` has the same formatting problem:

```
    rsa-pub: ssh-rsa AAAA...
      root@rancher
```

**Comment by ibuildthecloud** [comment]
How did you do the installation?  What does your cloud-config look like that you passed to rancheros-install?  Did it also have a newline in it?  Typically the cloud-config-processed doesn't have rsa-pub in it.

**Comment by bnoon** [comment]
I used `rancheros-install` with a cloud-config.yml file that looked like the following.  The ssh_authorized_keys value was all on one line:

```
#cloud-config

ssh_authorized_keys:
  - ssh-dss AAAA... noon@host

# Anything you can put in the rancher.yml
rancher:
  network:
    dns:
      nameservers:
      - 8.8.8.8
      - 8.8.4.4
    interfaces:
      eth0:
        address: 192.168.1.10/24
        gateway: 192.168.1.1
      eth1:
        address: 10.1.0.6/16
        gateway: 192.168.1.1
      lo:
        address: 127.0.0.1/8
```

The rss-pub entry is in `rancher-private.yml`

**Comment by ibuildthecloud** [comment]
Thanks, I'll try to reproduce on my side

**Comment by ibuildthecloud** [comment]
I tried this and can't reproduce the error.  Here is what I did.  I created an empty HD and booted the RancherOS v0.3.0 ISO.  I logged in with rancher/rancher and created /home/rancher/cc.yml with the below contents

```yaml
#cloud-config

ssh_authorized_keys:
  - ssh-dss AAAA... noon@host

# Anything you can put in the rancher.yml
rancher:
  network:
    dns:
      nameservers:
      - 8.8.8.8
      - 8.8.4.4
    interfaces:
      eth0:
        address: 192.168.1.10/24
        gateway: 192.168.1.1
      eth1:
        address: 10.1.0.6/16
        gateway: 192.168.1.1
      lo:
        address: 127.0.0.1/8
```

I then ran `sudo rancheros-install -d /dev/sda -c /home/rancher/cc.yml`.  After reboot it worked.

I tried `sudo rancherctl config export -p` and validated that it does indeed send a new line for `rsa-pub`.  This appears to be a valid yml syntax for strings in the "flow style".  I tried `sudo rancherctl config export -p | sudo rancherctl config import` and this also worked.
