### ISSUE TITLE
links: links key is not enabled for services

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/os#223]
In v0.3.0, `links` key is not enabled.

Example yaml:

```yaml
links: 
  - db
  - db:databse
```

**Comment by deniseschannon** [comment]
It doesn't show up when I do a `docker inspect` of a service that was enabled with links. 

Example service:

```yaml
nginx:
  links:
  - network
  net: host
  labels:
  - io.rancher.os.scope=system
  image: nginx
```
