### ISSUE TITLE
environment: valid syntax breaks booting of rancherOS

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/os#225]
v0.3.0

The syntax of my `environment` key in my yaml file causes the reboot to stop around here:

```bash
ip_tables: (C) 2000-2006 Netfilter Core Team
random: nonblocking pool is initialized
```

File that causes it to stop working:

```yaml
etcd:
  environment:
    ETCD_DISCOVERY: https://discovery.etcd.io/d1cd18f5ee1c1e2223aed6a1734719f7
  links:
  - network
  labels:
  - io.rancher.os.scope=system
  restart: always
  net: host
  image: quay.io/coreos/etcd:v2.0.4
  command: "--listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001"
```

If I enable the same service, but only change the environment section to the example below, RancherOS will boot up fine.

```yaml
etcd: 
  environment: 
     - ETCD_DISCOVERY=https://discovery.etcd.io/d1cd18f5ee1c1e2223aed6a1734719f7
...
...
```
