### ISSUE TITLE
"Invalid volume specification: /var/lib/cattle"

### ISSUE THREAD

**Issue by imikushin** [rancherio/os#275]
Given we have this in our compose file:
```yml
rancher-state:
  image: rancher/server:latest
  labels:
  - io.rancher.os.createonly=true
  - io.rancher.os.remove=false
  volumes:
  - /var/lib/cattle
  - /var/lib/mysql
rancherserver:
  image: rancher/server:latest
  restart: always
  volumes_from:
  - rancher-state
  ports:
  - 8080:8080
```

current os master boots with the following messages:
```
INFO[0005] [16/17] [rancherserver]: Started             
ERRO[0005] Failed to start: rancher-state : API error (500): Invalid volume specification: 
/var/lib/cattle
 
ERRO[0005] Failed [2/5] 40%                             
FATA[0005] API error (500): Invalid volume specification: /var/lib/cattle
```

So, two things:
1. What's wrong with the volume specification?
2. #274
