### ISSUE TITLE
Support adding and configuring new third party system services in RancherOS

### ISSUE THREAD

**Issue by smw355** [rancherio/os#72]
User should be able to create new system services as containers within RancherOS.

**Comment by imikushin** [comment]
### How does one start a service container on boot in RancherOS? 
(I've tried to add items to 'bootstrap_containers' key with rancherctl, but it just ignored it)

If a service container (not important, daemon or short lived) is named (and it probably should be), simply running the same `docker run` command on boot would result in error, e.g.: 

    Conflict. The name "nginx" is already in use... You have to delete (or rename) that container to be able to reuse that name. 

This is something I suffered from when working on rancheros-k8s, and it's the same with launching Azure agent on boot. 
This has to be addressed with some sort of service management tool. 
rancherctl / cloud-config?

**Comment by ibuildthecloud** [comment]
You can't change bootstrap_containers or system_container configuration.  Those are reserved for the code only.  What I'm working on right now is that you can add additional containers to the system container by specifying a Docker compose template.  For example, in `/var/lib/rancher/conf/rancher.yml` you will have

```yaml
services:
- http://.../something.yml
- /var/lib/rancher/conf/etcd.yml
```

You can refer to a local file or a URL.  In the compose yml it will then look something like (this is based off your etcd/flannel PR):

```yaml
etcd:
  links:
  - network
  restart: always
  net: host
  image: quay.io/coreos/etcd:v2.0.4
  command: "--listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001"
```

RancherOS will then name that container as `etcd` but then deal with deleting, renaming, or creating new containers if needed.

**Comment by imikushin** [comment]
Great you're already working on it. I'd love to take a look at the code and to test. 

BTW, it might be a good idea to specify whether a service is a system level (run by system-docker) or user level service (run by [user]docker).

**Comment by wblankenship** [comment]
I was considering a similar problem the other day. Without `init.d` to manage the lifecycle of services, what should be the solution for not only starting containers on boot, but making sure they are persistant

In the conversation I had with myself, I settled on letting userland tools do the heavy work (like monit) and keeping that code out of the os tools (thus I didn't open an issue), but it seems like some of this work is moving in that direction...Thoughts?

**Comment by imikushin** [comment]
Also, what's currently (as of v0.2.1) the best way to start services?
`/opt/rancher/bin/start.sh` doesn't make it: #106

**Comment by ibuildthecloud** [comment]
@imikushin `/opt/rancher/bin/start.sh` is still the best way (albeit terrible).  I don't think #106 is related to start.sh

**Comment by ibuildthecloud** [comment]
@wblankenship The intention at the moment, unless somebody thinks it's a terrible idea, is to define all system service and user containers that should start on boot in a compose syntax.  The execution the template is specific to RancherOS because it does a lot to handle to make the service persistant or ephermeal and then handle creating new containers if something changes.

For example, in the dev code I have right now, all the prepackaged system services in RancherOS looks like:

```yaml
all-volumes:
  image: state
  labels:
  - io.rancher.os.createonly=true
  net: none
  privileged: true
  read_only: true
  volumes_from:
  - docker-volumes
  - command-volumes
  - user-volumes
  - system-volumes
cloud-init:
  image: cloudinit
  labels:
  - io.rancher.os.reloadconfig=true
  links:
  - cloud-init-pre
  - network
  net: host
  privileged: true
  volumes_from:
  - command-volumes
  - system-volumes
cloud-init-pre:
  environment:
  - CLOUD_INIT_NETWORK=false
  image: cloudinit
  labels:
  - io.rancher.os.reloadconfig=true
  net: host
  privileged: true
  volumes_from:
  - command-volumes
  - system-volumes
command-volumes:
  image: state
  labels:
  - io.rancher.os.createonly=true
  net: none
  privileged: true
  read_only: true
  volumes:
  - /init:/sbin/halt:ro
  - /init:/sbin/poweroff:ro
  - /init:/sbin/reboot:ro
  - /init:/sbin/shutdown:ro
  - /init:/sbin/netconf:ro
  - /init:/usr/bin/cloud-init:ro
  - /init:/usr/bin/rancherctl:ro
  - /init:/usr/bin/respawn:ro
  - /init:/usr/bin/system-docker:ro
  - /lib/modules:/lib/modules:ro
  - /usr/bin/docker:/usr/bin/docker:ro
console:
  image: console
  labels:
  - io.rancher.os.detach=true
  - io.rancher.os.remove=true
  links:
  - cloud-init
  net: host
  pid: host
  ipc: host
  privileged: true
  restart: always
  volumes_from:
  - all-volumes
docker-volumes:
  image: state
  labels:
  - io.rancher.os.createonly=true
  net: none
  privileged: true
  read_only: true
  volumes:
  - /var/lib/rancher:/var/lib/rancher
  - /var/lib/docker:/var/lib/docker
  - /var/lib/system-docker:/var/lib/system-docker
network:
  cap_add:
  - NET_ADMIN
  image: network
  links:
  - cloud-init-pre
  net: host
  volumes_from:
  - command-volumes
  - system-volumes
ntp:
  image: ntp
  labels:
  - io.rancher.os.detach=true
  links:
  - cloud-init
  - network
  net: host
  privileged: true
syslog:
  image: syslog
  labels:
  - io.rancher.os.detach=true
  links:
  - cloud-init
  - network
  net: host
  privileged: true
  volumes_from:
  - system-volumes
system-volumes:
  image: state
  labels:
  - io.rancher.os.createonly=true
  net: none
  privileged: true
  read_only: true
  volumes:
  - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
  - /var/lib/rancher/conf:/var/lib/rancher/conf
  - /lib/modules:/lib/modules:ro
  - /var/run:/var/run
  - /var/log:/var/log
udev:
  environment:
  - DAEMON=true
  image: udev
  labels:
  - io.rancher.os.detach=true
  net: host
  privileged: true
  volumes:
  - /dev:/host/dev
  - /lib/modules:/lib/modules:ro
  - /lib/firmware:/lib/firmware:ro
user-volumes:
  image: state
  labels:
  - io.rancher.os.createonly=true
  net: none
  privileged: true
  read_only: true
  volumes:
  - /home:/home
  - /opt:/opt
userdocker:
  image: userdocker
  labels:
  - io.rancher.os.detach=true
  links:
  - network
  net: host
  pid: host
  ipc: host
  privileged: true
  volumes_from:
  - all-volumes
```

Using the rancher.yml (or cloud config), you will then be able to specific more templates to load.
