### ISSUE TITLE
failed to install rancheros on VirtualBox

### ISSUE THREAD

**Issue by ifeiteng** [rancherio/os#88]
first, the `rancheros-install` is not exist, i pull it from `/scripts/dockerimages/scripts/rancheros-install`
then, i use `sudo rancheros-install -d /dev/sda -c ./cloud_data.yml -v v0.1.2 -t generic`
it show me `The file /dev/sda1 is not exist and no size was specified`

**Comment by ibuildthecloud** [comment]
Sorry about that.  We just about to cut a release of RancherOS that includes this script but we merged the README to master.  So the docs are not in sync with the latest release.

**Comment by wblankenship** [comment]
Good to know! I thought I was loosing my mind. :smile:

**Comment by cloudnautique** [comment]
@ifeiteng do you have any more of the output you'd be willing to share via a gist or something?

**Comment by fernando-cloudster** [comment]
Any ETA on the new release? Or any other way to install on vbox/vmware?

**Comment by cloudnautique** [comment]
@fernando-cloudster Soon! 

If you are feeling adventurous: [rancherio/os-installer](https://github.com/rancherio/os-installer) outlines the processes.

**Comment by fernando-cloudster** [comment]
Hah! here I go :D thanks!

**Comment by fernando-cloudster** [comment]
Guess I'll join the OP on waiting, unless anybody got some ideas for me.

The steps to install on the disk were actually really easy, I was expecting a lot of pain :dancers: 

```
sudo system-docker run --privileged --net=host -it --entrypoint=/scripts/set-disk-partitions rancher/os-installer:v0.1.2 /dev/sda
sudo system-docker run --privileged --net=host -it --volumes-from=user-volumes rancher/os-installer:v0.1.2 -d /dev/sda -t generic -c /opt/cloud 
```
and boom its installed, so I guess the issue is in my cloud-init file.

```
#cloud-config
users:
  - name: myuser
    passwd: $1$cccIdjm...(generated with openssl passwd -1)
    groups:
      - sudo
      - docker
      - rancher
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1...(my pubkey)
```
any ideas on what I did wrong?
