### ISSUE TITLE
Trying to get an IP address automatically for all interfaces at boot time.

### ISSUE THREAD

**Issue by fatihusta** [rancherio/os#98]
This process extends the startup process.
Automatic IP undistributed a network in this process is even longer.
Network settings must be set by the user. or to get an IP address automatically is only open for the first interface will be more accurate.

System: VirtualBox

**Comment by ibuildthecloud** [comment]
The networking is configurable through the rancher.yml and cloud-init.  The documentation is at https://github.com/rancherio/os/blob/master/docs/config.md#networking.  In the `/var/lib/rancher/conf/rancher.yml` you will need to do something like:

```yaml
network:
  interfaces:
    eth*:
      # Disable DHCP for all interfaces
      dhcp: false
    eth1:
      address: 192.168.0.5
      gateway: 192.168.0.1
```

If you are using the cloud-init, do the same as above but nest everything under the `rancher` key.
